development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: irochilog_development
  pool: 5
  username: irochilog
  password: irochilog
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: irochilog_test
  pool: 5
  username: irochilog
  password: irochilog
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: irochilog_production
  pool: 5
  username: irochilog
  password: irochilog
  host: localhost
